spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(EfqZN6R7drkV3Sd5Zw1O/nsKv3pvxl+PYazSEvvv5VU=)
    password: ENC(qWsxatTsJ/p7WPaXQrl6GhzuJFNU8ABurfPDynYRaBY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?

  data:
    redis:
      host: localhost
      port: 6379 # redis port

# for encode of password
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# hibernate logging
logging:
  level:
    p6spy: info
    org:
      springframework:
        security: DEBUG
